default_windows:
  - name: "neovim"
    command: "nvim"
  - name: "terminal"
  - name: "mprocs"
    command: "mprocs"
  - name: "terminal"
    panes:
    - split_direction: "vertical"
      size: 25  # percentage width of a vertically split pane
    - split_direction: "horizontal"
      size: 40

