#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew bundle install
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
curl https://raw.githubusercontent.com/josean-dev/dev-environment-files/main/.config/alacritty/themes/themes/coolnight.toml --output ~/.config/alacritty/themes/themes/coolnight.toml
cargo install tmux-sessionizer
cargo install tmuxedo

ln -s ~/.config/git/gitconfig.ini ~/.gitconfig
ln -s ~/.config/zsh/zshrc ~/.zshrc

