alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"
alias l="ls -l"
alias ll="ls -l"
alias em="emacs -nw"
alias gca="git commit --amend --no-edit --reset-author --no-verify"
alias copy_branch="git branch --show-current | pbcopy"
alias get_idf='. $HOME/esp/esp-idf/export.sh'

export PATH=$HOME/Personal/flutter/bin:$PATH
export PATH=$PATH:~/.cargo/bin/
export IDF_PATH=$HOME/esp/esp-idf
export PATH="$IDF_PATH/tools:$PATH"
export TMUX_PLUGIN_MANAGER_PATH=$HOME/.config/tmux/plugins
export PATH="$PATH:/Users/aran.borkum/.local/bin"
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ---- Starship -----
eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# ----- Bat (better cat) -----
export BAT_THEME=tokyonight_night
alias cat="bat"

# ---- FZF -----
# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# -- Use fd instead of fzf --
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# ----- Invoke auto complete -----
if [ -f ~/.config/zsh/invoke.zsh ]; then
	source ~/.config/zsh/invoke.zsh
fi

# ----- Kraken specific zsh configurations -----
if [ -f ~/.config/zsh/kraken.zsh ]; then
  source ~/.config/zsh/kraken.zsh
fi
#
# ----- Git foo -----
if [ -f ~/.config/zsh/git_foo.zsh ]; then
  source ~/.config/zsh/git_foo.zsh
fi

# ----- Pyenv -----
eval "$(/opt/homebrew/bin/brew shellenv)"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ----- Node version manager -----
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

fpath+=~/.zfunc; autoload -Uz compinit; compinit

zstyle ':completion:*' menu select

. "$HOME/.cargo/env"
